name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/minio-fixture-generator

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1) Клонируем репозиторий, чтобы metadata-action видел git-данные
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Входим в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Готовим buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4) Генерируем список тегов: latest для main и sha-таг
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,ref=refs/heads/main,format=latest
            type=sha

      # 5) Собираем и пушим образ со всеми тегами из meta.outputs.tags
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
