name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:     
      type=raw,value=latest,enable={{is_default_branch}}
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/minio-fixture-generator

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          sbom: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
